- name: Qodana Scan
  uses: JetBrains/qodana-action@v2024.1.3
  with:
    # Enable all checks by running the full analysis profile
    analysis-profile: full

    # Ensure all possible issues are reported
    additional-args: "--run-all-checks --fail-threshold=0"

    # Store Qodana results for further analysis
    results-dir: ${{ runner.temp }}/qodana/results

    # Use cache for efficiency
    cache-dir: ${{ runner.temp }}/qodana/caches
    use-caches: true

    # Cache configuration
    primary-cache-key: qodana-2024.1-${{ github.ref }}-${{ github.sha }}
    additional-cache-key: qodana-2024.1-${{ github.ref }}
    cache-default-branch-only: false

    # Upload results for analysis
    upload-result: true
    artifact-name: qodana-analysis-results

    # Ensure detailed annotations are visible in GitHub UI
    use-annotations: true

    # Run Qodana on all files, not just changed files in PR
    pr-mode: false

    # Prevent automatic commenting on PRs
    post-pr-comment: false

    # GitHub authentication
    github-token: ${{ github.token }}

    # Automatically push fixes to a pull request
    push-fixes: pull-request
    commit-message: "🔧 Auto-fix by Qodana"

    # Use latest stable version (not nightly)
    use-nightly: false


